//
//  Font.swift
//  Restaurant
//
//  Created by PGK Shiva Kumar on 31/05/23.
//

import Foundation
import UIKit

class Fonts {
    
    static let shared: Fonts = Fonts()
    
    private init() {  }
    
    let blackMin = UIFont.init(name: "Poppins-Black", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .black)
    let black1 = UIFont.init(name: "Poppins-Black", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .black)
    let black2 = UIFont.init(name: "Poppins-Black", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .black)
    let black3 = UIFont.init(name: "Poppins-Black", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .black)
    let black4 = UIFont.init(name: "Poppins-Black", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .black)
    let black5 = UIFont.init(name: "Poppins-Black", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .black)
    let black6 = UIFont.init(name: "Poppins-Black", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .black)
    let black7 = UIFont.init(name: "Poppins-Black", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .black)
    
    let blackItalicMin = UIFont.init(name: "Poppins-BlackItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .black)
    let blackItalic1 = UIFont.init(name: "Poppins-BlackItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .black)
    let blackItalic2 = UIFont.init(name: "Poppins-BlackItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .black)
    let blackItalic3 = UIFont.init(name: "Poppins-BlackItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .black)
    let blackItalic4 = UIFont.init(name: "Poppins-BlackItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .black)
    let blackItalic5 = UIFont.init(name: "Poppins-BlackItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .black)
    let blackItalic6 = UIFont.init(name: "Poppins-BlackItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .black)
    let blackItalic7 = UIFont.init(name: "Poppins-BlackItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .black)
    
    let boldMin = UIFont.init(name: "Poppins-Bold", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .bold)
    let bold1 = UIFont.init(name: "Poppins-Bold", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .bold)
    let bold2 = UIFont.init(name: "Poppins-Bold", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .bold)
    let bold3 = UIFont.init(name: "Poppins-Bold", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .bold)
    let bold4 = UIFont.init(name: "Poppins-Bold", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .bold)
    let bold5 = UIFont.init(name: "Poppins-Bold", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .bold)
    let bold6 = UIFont.init(name: "Poppins-Bold", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .bold)
    let bold7 = UIFont.init(name: "Poppins-Bold", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .bold)
    
    let boldItalicMin = UIFont.init(name: "Poppins-BoldItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .regular)
    let boldItalic1 = UIFont.init(name: "Poppins-BoldItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .regular)
    let boldItalic2 = UIFont.init(name: "Poppins-BoldItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .regular)
    let boldItalic3 = UIFont.init(name: "Poppins-BoldItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .regular)
    let boldItalic4 = UIFont.init(name: "Poppins-BoldItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .regular)
    let boldItalic5 = UIFont.init(name: "Poppins-BoldItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .regular)
    let boldItalic6 = UIFont.init(name: "Poppins-BoldItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .regular)
    let boldItalic7 = UIFont.init(name: "Poppins-BoldItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .regular)
    
    let extraBoldMin = UIFont.init(name: "Poppins-ExtraBold", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .heavy)
    let extraBold1 = UIFont.init(name: "Poppins-ExtraBold", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .heavy)
    let extraBold2 = UIFont.init(name: "Poppins-ExtraBold", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .heavy)
    let extraBold3 = UIFont.init(name: "Poppins-ExtraBold", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .heavy)
    let extraBold4 = UIFont.init(name: "Poppins-ExtraBold", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .heavy)
    let extraBold5 = UIFont.init(name: "Poppins-ExtraBold", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .heavy)
    let extraBold6 = UIFont.init(name: "Poppins-ExtraBold", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .heavy)
    let extraBold7 = UIFont.init(name: "Poppins-ExtraBold", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .heavy)
    
    let extraBoldItalicMin = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .heavy)
    let extraBoldItalic1 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .heavy)
    let extraBoldItalic2 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .heavy)
    let extraBoldItalic3 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .heavy)
    let extraBoldItalic4 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .heavy)
    let extraBoldItalic5 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .heavy)
    let extraBoldItalic6 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .heavy)
    let extraBoldItalic7 = UIFont.init(name: "Poppins-ExtraBoldItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .heavy)
    
    let extraLightMin = UIFont.init(name: "Poppins-ExtraLight", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .ultraLight)
    let extraLight1 = UIFont.init(name: "Poppins-ExtraLight", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .ultraLight)
    let extraLight2 = UIFont.init(name: "Poppins-ExtraLight", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .ultraLight)
    let extraLight3 = UIFont.init(name: "Poppins-ExtraLight", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .ultraLight)
    let extraLight4 = UIFont.init(name: "Poppins-ExtraLight", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .ultraLight)
    let extraLight5 = UIFont.init(name: "Poppins-ExtraLight", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .ultraLight)
    let extraLight6 = UIFont.init(name: "Poppins-ExtraLight", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .ultraLight)
    let extraLight7 = UIFont.init(name: "Poppins-ExtraLight", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .ultraLight)
    
    let extraLightItalicMin = UIFont.init(name: "Poppins-ExtraLightItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .ultraLight)
    let extraLightItalic1 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .ultraLight)
    let extraLightItalic2 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .ultraLight)
    let extraLightItalic3 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .ultraLight)
    let extraLightItalic4 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .ultraLight)
    let extraLightItalic5 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .ultraLight)
    let extraLightItalic6 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .ultraLight)
    let extraLightItalic7 = UIFont.init(name: "Poppins-ExtraLightItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .ultraLight)
    
    let italicMin = UIFont.init(name: "Poppins-Italic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .light)
    let italic1 = UIFont.init(name: "Poppins-Italic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .light)
    let italic2 = UIFont.init(name: "Poppins-Italic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .light)
    let italic3 = UIFont.init(name: "Poppins-Italic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .light)
    let italic4 = UIFont.init(name: "Poppins-Italic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .light)
    let italic5 = UIFont.init(name: "Poppins-Italic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .light)
    let italic6 = UIFont.init(name: "Poppins-Italic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .light)
    let italic7 = UIFont.init(name: "Poppins-Italic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .light)
    
    let lightMin = UIFont.init(name: "Poppins-Light", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .light)
    let light1 = UIFont.init(name: "Poppins-Light", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .light)
    let light2 = UIFont.init(name: "Poppins-Light", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .light)
    let light3 = UIFont.init(name: "Poppins-Light", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .light)
    let light4 = UIFont.init(name: "Poppins-Light", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .light)
    let light5 = UIFont.init(name: "Poppins-Light", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .light)
    let light6 = UIFont.init(name: "Poppins-Light", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .light)
    let light7 = UIFont.init(name: "Poppins-Light", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .light)
    
    let lightItalicMin = UIFont.init(name: "Poppins-LightItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .light)
    let lightItalic1 = UIFont.init(name: "Poppins-LightItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .light)
    let lightItalic2 = UIFont.init(name: "Poppins-LightItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .light)
    let lightItalic3 = UIFont.init(name: "Poppins-LightItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .light)
    let lightItalic4 = UIFont.init(name: "Poppins-LightItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .light)
    let lightItalic5 = UIFont.init(name: "Poppins-LightItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .light)
    let lightItalic6 = UIFont.init(name: "Poppins-LightItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .light)
    let lightItalic7 = UIFont.init(name: "Poppins-LightItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .light)
    
    let mediumMin = UIFont.init(name: "Poppins-Medium", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .medium)
    let medium1 = UIFont.init(name: "Poppins-Medium", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .medium)
    let medium2 = UIFont.init(name: "Poppins-Medium", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .medium)
    let medium3 = UIFont.init(name: "Poppins-Medium", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .medium)
    let medium4 = UIFont.init(name: "Poppins-Medium", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .medium)
    let medium5 = UIFont.init(name: "Poppins-Medium", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .medium)
    let medium6 = UIFont.init(name: "Poppins-Medium", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .medium)
    let medium7 = UIFont.init(name: "Poppins-Medium", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .medium)
    
    let mediumItalicMin = UIFont.init(name: "Poppins-MediumItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .medium)
    let mediumItalic1 = UIFont.init(name: "Poppins-MediumItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .medium)
    let mediumItalic2 = UIFont.init(name: "Poppins-MediumItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .medium)
    let mediumItalic3 = UIFont.init(name: "Poppins-MediumItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .medium)
    let mediumItalic4 = UIFont.init(name: "Poppins-MediumItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .medium)
    let mediumItalic5 = UIFont.init(name: "Poppins-MediumItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .medium)
    let mediumItalic6 = UIFont.init(name: "Poppins-MediumItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .medium)
    let mediumItalic7 = UIFont.init(name: "Poppins-MediumItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .medium)
    
    let regularMin = UIFont.init(name: "Poppins-Regular", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .regular)
    let regular1 = UIFont.init(name: "Poppins-Regular", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .regular)
    let regular2 = UIFont.init(name: "Poppins-Regular", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .regular)
    let regular3 = UIFont.init(name: "Poppins-Regular", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .regular)
    let regular4 = UIFont.init(name: "Poppins-Regular", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .regular)
    let regular5 = UIFont.init(name: "Poppins-Regular", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .regular)
    let regular6 = UIFont.init(name: "Poppins-Regular", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .regular)
    let regular7 = UIFont.init(name: "Poppins-Regular", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .regular)
    
    let semiboldMin = UIFont.init(name: "Poppins-SemiBold", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .semibold)
    let semibold1 = UIFont.init(name: "Poppins-SemiBold", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .semibold)
    let semibold2 = UIFont.init(name: "Poppins-SemiBold", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .semibold)
    let semibold3 = UIFont.init(name: "Poppins-SemiBold", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .semibold)
    let semibold4 = UIFont.init(name: "Poppins-SemiBold", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .semibold)
    let semibold5 = UIFont.init(name: "Poppins-SemiBold", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .semibold)
    let semibold6 = UIFont.init(name: "Poppins-SemiBold", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .semibold)
    let semibold7 = UIFont.init(name: "Poppins-SemiBold", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .semibold)
    
    let semiboldItalicMin = UIFont.init(name: "Poppins-SemiBoldItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .semibold)
    let semiboldItalic1 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .semibold)
    let semiboldItalic2 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .semibold)
    let semiboldItalic3 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .semibold)
    let semiboldItalic4 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .semibold)
    let semiboldItalic5 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .semibold)
    let semiboldItalic6 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .semibold)
    let semiboldItalic7 = UIFont.init(name: "Poppins-SemiBoldItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .semibold)
    
    let thinMin = UIFont.init(name: "Poppins-Thin", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .thin)
    let thin1 = UIFont.init(name: "Poppins-Thin", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .thin)
    let thin2 = UIFont.init(name: "Poppins-Thin", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .thin)
    let thin3 = UIFont.init(name: "Poppins-Thin", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .thin)
    let thin4 = UIFont.init(name: "Poppins-Thin", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .thin)
    let thin5 = UIFont.init(name: "Poppins-Thin", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .thin)
    let thin6 = UIFont.init(name: "Poppins-Thin", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .thin)
    let thin7 = UIFont.init(name: "Poppins-Thin", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .thin)
    
    let thinItalicMin = UIFont.init(name: "Poppins-ThinItalic", size: 10) ?? UIFont.systemFont(ofSize: 10, weight: .thin)
    let thinItalic1 = UIFont.init(name: "Poppins-ThinItalic", size: 12) ?? UIFont.systemFont(ofSize: 12, weight: .thin)
    let thinItalic2 = UIFont.init(name: "Poppins-ThinItalic", size: 14) ?? UIFont.systemFont(ofSize: 14, weight: .thin)
    let thinItalic3 = UIFont.init(name: "Poppins-ThinItalic", size: 16) ?? UIFont.systemFont(ofSize: 16, weight: .thin)
    let thinItalic4 = UIFont.init(name: "Poppins-ThinItalic", size: 18) ?? UIFont.systemFont(ofSize: 18, weight: .thin)
    let thinItalic5 = UIFont.init(name: "Poppins-ThinItalic", size: 20) ?? UIFont.systemFont(ofSize: 20, weight: .thin)
    let thinItalic6 = UIFont.init(name: "Poppins-ThinItalic", size: 22) ?? UIFont.systemFont(ofSize: 22, weight: .thin)
    let thinItalic7 = UIFont.init(name: "Poppins-ThinItalic", size: 24) ?? UIFont.systemFont(ofSize: 24, weight: .thin)
}
